//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_CRM_Phones
    {
        public int PhoneId { get; set; }
        public string PhoneNumber { get; set; }
        public int ContactId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual t_CRM_Contacts t_CRM_Contacts { get; set; }
    }
}
